// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _20240723_SqlDb_Gai.Models;

#nullable disable

namespace _20240723_SqlDb_Gai.Migrations
{
    [DbContext(typeof(CarContext))]
    partial class CarContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ColorId");

                    b.Property<int>("MarkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_MarkId");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("VinCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)")
                        .HasDefaultValue("none");

                    b.Property<float>("Volume")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MarkId");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IndexNumber");

                    b.ToTable("cars", null, t =>
                        {
                            t.HasCheckConstraint("ValidVolume", "Volume > 0 AND Volume <= 6");
                        });
                });

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RAL")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("colors", (string)null);
                });

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaintThkMax")
                        .HasColumnType("int");

                    b.Property<int>("PaintThkMin")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("marks", (string)null);
                });

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Car", b =>
                {
                    b.HasOne("_20240723_SqlDb_Gai.Models.Color", "_Color")
                        .WithMany("Cars")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_20240723_SqlDb_Gai.Models.Mark", "_Mark")
                        .WithMany("Cars")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Color");

                    b.Navigation("_Mark");
                });

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Color", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("_20240723_SqlDb_Gai.Models.Mark", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
